security:
  starter:
    xss:
      antisamy:
        enable: false
        policy-file: antisamy-ebay.xml
      esapi:
        enable: false
      jsoup:
        enable: false
        whitelist: relaxed