security:
  starter:
    xss:
      antisamy:
        enable: false
        policy-file: antisamy-ebay.xml
      esapi:
        enable: false
      jsoup:
        enable: false
        whitelist: relaxed
      html-sanitizer:
        enable: false
        allow-elements: h1, div